In [1]:
### Correlation Matrix

In [5]:
### Matplotlib

In [2]:
### Heatmap

In [3]:
### Relationship between : Num - Num , Num - Cat, Cat - Cat

In [4]:
### Univariate, Bivariate, Multivariate Analysis

In [7]:
### Plotting -> Histogram, Pairplot

## Numpy -> Array, Array Operation, Sorting, Accessing, Slicing

In [9]:
import numpy as np

## Array Initialization

In [16]:
# 1d - vector
np.array([1,2,3])

array([1, 2, 3])

In [17]:
type(np.array([1,2,3]))

numpy.ndarray

In [18]:
# 2d - matrix
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [19]:
# 3d - tensor
np.array([
    [
        [1,2,],
        [3,4]
    ],
    [
        [5,6,],
        [7,8]
    ]
])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
# dtype
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [21]:
np.array([12,23,34],dtype=float)

array([12., 23., 34.])

In [23]:
np.array([1.2,2.3,4.5],dtype=int)

array([1, 2, 4])

In [25]:
np.array([1,2,4],dtype=complex)

array([1.+0.j, 2.+0.j, 4.+0.j])

In [27]:
# np.range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [65]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [32]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
# np.ones and np.zeros

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# np.random
np.random.random((3,4))

array([[0.59550044, 0.00579817, 0.32121989, 0.0832738 ],
       [0.91526192, 0.68288792, 0.95636949, 0.54913213],
       [0.70758937, 0.31315471, 0.30241215, 0.4194455 ]])

In [54]:
# np.linspace => In given range it creates array at equal distance.
np.linspace(start=-10,stop=10,num=20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [55]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [68]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [69]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [71]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
# ndim
a1.ndim

1

In [73]:
a2.ndim

2

In [74]:
a3.ndim

3

In [75]:
# shape
a1.shape

(10,)

In [76]:
a2.shape

(3, 4)

In [77]:
a3.shape

(2, 2, 2)

In [78]:
# size
a1.size

10

In [79]:
a2.size

12

In [80]:
a3.size

8

In [87]:
# itemsize 
a1.itemsize
# 4 bit

4

In [88]:
a2.itemsize
# 8 bit

8

In [89]:
a3.itemsize
# 4 bit

4

In [84]:
# dtype
a1.dtype

dtype('int32')

In [85]:
a2.dtype

dtype('float64')

In [86]:
a3.dtype

dtype('int32')

## Changing Datatype

In [92]:
a3.dtype

dtype('int32')

In [93]:
# astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

## Array Operations

In [108]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [109]:
# Scaler Functions
# Arithmetic
print(a1 + 2)
print(a1 - 2)
print(a1 * 2)
print(a1 / 2)
print(a1 ** 2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [110]:
# Relational
a1 > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [112]:
a2 == 20

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [113]:
# Vector Operation
# Arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [114]:
a2 - a1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

## Array Functions

In [128]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [129]:
a1

array([[77., 79., 43.],
       [65., 23., 82.],
       [77., 67., 39.]])

In [140]:
# max/min/sum/prod

In [141]:
print(np.max(a1))
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))

82.0
[77. 79. 82.]
[79. 82. 77.]


In [142]:
print(np.min(a1))
print(np.min(a1,axis=0))
print(np.min(a1,axis=1))

23.0
[65. 23. 39.]
[43. 23. 39.]


In [143]:
print(np.sum(a1))
print(np.sum(a1,axis=0))
print(np.sum(a1,axis=1))

552.0
[219. 169. 164.]
[199. 170. 183.]


In [144]:
print(np.prod(a1))
print(np.prod(a1,axis=0))
print(np.prod(a1,axis=1))

6451659700195710.0
[385385. 121739. 137514.]
[261569. 122590. 201201.]


In [145]:
# Mean/Median/Std/Var

In [150]:
np.mean(a1)
# axis=0,axis=1

61.333333333333336

In [151]:
np.median(a1)
# axis=0,axis=1

67.0

In [153]:
np.std(a1)
# axis=0,axis=1

19.94436706886879

In [156]:
np.var(a1)
# 19.94436706886879 ** 2

397.7777777777778

In [146]:
# trigonomoetric functions

In [159]:
np.sin(a1)

array([[ 0.99952016, -0.44411267, -0.83177474],
       [ 0.82682868, -0.8462204 ,  0.31322878],
       [ 0.99952016, -0.85551998,  0.96379539]])

In [160]:
np.cos(a1)

array([[-0.03097503, -0.89597095,  0.5551133 ],
       [-0.56245385, -0.53283302,  0.9496777 ],
       [-0.03097503, -0.5177698 ,  0.26664293]])

In [161]:
np.tan(a1)

array([[-32.26857578,   0.49567753,  -1.49838734],
       [ -1.47003826,   1.58815308,   0.32982641],
       [-32.26857578,   1.65231726,   3.61455441]])

In [162]:
# Dot Product

In [163]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [164]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [166]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [170]:
# Log and Exponent
np.log(a2)

C:\Users\Admin\AppData\Local\Temp\ipykernel_28108\4288203401.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [171]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [177]:
# round/floor/ceil
np.round(np.random.random((3,3))*20)

array([[12., 18.,  4.],
       [ 9.,  4.,  8.],
       [ 4.,  2., 18.]])

In [178]:
np.floor(np.random.random((3,3))*20)

array([[14.,  9., 11.],
       [19.,  1., 15.],
       [10., 19., 14.]])

In [180]:
np.ceil(np.random.random((3,3))*20)

array([[13.,  4., 17.],
       [ 6.,  4., 18.],
       [12., 20.,  9.]])

## Indexing and Slicing

### Indexing

In [182]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [183]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [186]:
a1[0]

0

In [187]:
a1[:4]

array([0, 1, 2, 3])

In [189]:
a1[-4::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [190]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
# a2[row,column]
a2[1,1]

5

In [192]:
a2[2,2]

10

In [193]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [194]:
a3[1,0,1]

5

In [195]:
a3[0,1,0]

2

In [196]:
a3[1,1,0]

6

## Slicing

In [197]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
a1[3:8]

array([3, 4, 5, 6, 7])

In [200]:
a1[-3:-8:-1]

array([7, 6, 5, 4, 3])

In [202]:
a1[3:8:2]

array([3, 5, 7])

In [203]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
a2[0,:]

array([0, 1, 2, 3])

In [212]:
a2[:,2]

array([ 2,  6, 10])

In [214]:
a2[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [215]:
a2[::2,::2]

array([[ 0,  2],
       [ 8, 10]])

In [216]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [219]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [221]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [225]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [227]:
a3 = np.arange(27).reshape((3,3,3))

In [228]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [231]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [232]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [234]:
a3[0][1]

array([3, 4, 5])

In [235]:
a3[0,1,:]

array([3, 4, 5])

In [236]:
a3[1,:,1]

array([10, 13, 16])

In [238]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [240]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [250]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [251]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [248]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [249]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [244]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [247]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [256]:
# np.nditer() will convert any number of dimention into one dimention array.
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [258]:
# reshape
a1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [260]:
# Transpose -> row -> column , column -> row
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [261]:
# ravel -> convert any number dimentional array to 1d array
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

### Horizontal Stacking -> Column wise

In [266]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [267]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

### Vertical Stacking -> Row wise

In [268]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

### Horizontal Splitting -> Column wise

In [270]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [274]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### Vertical Splitting -> Row wise

In [280]:
a5 = np.vstack((a5,[33,11,22,55]))

In [281]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [33, 11, 22, 55]])

In [282]:
np.vsplit(a5,4)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]]),
 array([[33, 11, 22, 55]])]

In [283]:
np.vsplit(a5,2)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [33, 11, 22, 55]])]